ark_track: # this needs to match the profile: in your dbt_project.yml file
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      # keyfile: "{{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE') }}" # replace this with the full path to your keyfile
      # project: "{{ env_var('DBT_GOOGLE_PROJECT') }}" # Replace this with your project id
      # dataset: "{{ env_var('DBT_GOOGLE_BIGQUERY_DATASET') }}" # Replace this with dbt_your_name, e.g. dbt_bob
      keyfile: "C:/Users/channo/OneDrive - The Chinese University of Hong Kong/Github Code/fork/project-ark/dbt-service-account.json" # replace this with the full path to your keyfile
      project: "pragmatic-ratio-319408" # Replace this with your project id
      dataset: "dbt_ark" # Replace this with dbt_your_name, e.g. dbt_bob
      threads: 4 
      timeout_seconds: 300
      location: US
      priority: interactive
